[package]
name = "rustz80emu"
version = "0.1.0"
authors = ["Andrei Faur <da3drus@gmail.com>"]
license = "MIT"

[dependencies]
enum_primitive = "0.1.0"
num = "0.1.34"
bitflags = "0.7.0"

[lib]
name = "z80emulib"
path = "src/lib.rs"
test = false
doctest = false

[[bin]]
name = "z80emubin"
path = "src/main.rs"
test = false
